Repository nasa/to_lab, pull requests merged in 2020-12, with the labels that each got.

#69 Fix #66, Implement message alignment pattern
  fsw/platform_inc/to_lab_sub_table.h
  fsw/src/to_lab_app.c
  fsw/src/to_lab_msg.h
  fsw/tables/to_lab_sub.c
Labels: CCB-20201202, IC-20201208, dependency

#70 to_lab Integration Candidate: 2020-12-08
  README.md
  fsw/platform_inc/to_lab_sub_table.h
  fsw/src/to_lab_app.c
  fsw/src/to_lab_msg.h
  fsw/src/to_lab_version.h
  fsw/tables/to_lab_sub.c
Labels: IC-20201208

#74 Fix #71, Remove all only from telemetry pipe
  fsw/src/to_lab_app.c
  fsw/src/to_lab_events.h
Labels: CCB-20201216

#75 to_lab Integration Candidate: 2020-12-22
  README.md
  fsw/src/to_lab_app.c
  fsw/src/to_lab_events.h
  fsw/src/to_lab_version.h
Labels: IC-20201222
