Repository nasa/to_lab, pull requests merged in 2020-08, with the labels that each got.

#51 Fix #50, Mark end of valid MsgId subscriptions
  CMakeLists.txt
  README.md
  fsw/src/to_lab_app.c
  fsw/tables/to_lab_sub.c
Labels: CCB-20200729, CCB-FastTrack, IC-20200729, bug

#52 Close #49, Add build number and baseline to version file
  fsw/src/to_lab_app.c
  fsw/src/to_lab_version.h
Labels: CCB-FastTrack, IC-20200729

#53 Integration Candidate 2020-07-29
  CMakeLists.txt
  README.md
  fsw/src/to_lab_app.c
  fsw/src/to_lab_version.h
  fsw/tables/to_lab_sub.c
Labels: IC-20200729

#55 Fix #54, remove reference to CFE_ES_SHELL_TLM
  fsw/tables/to_lab_sub.c
Labels: CCB-20200819, CCB-READY, IC-20200819, code reviewed

#58 Integration Candidate: 2020-08-19
  README.md
  fsw/src/to_lab_version.h
  fsw/tables/to_lab_sub.c
Labels: IC-20200819

#57 Fix #56, Add header guard to to_lab_sub_table.h
  fsw/platform_inc/to_lab_sub_table.h
Labels: CCB-20200826, CCB-FastTrack, IC-20200826, enhancement
