Repository nasa/to_lab, pull requests merged in 2020-06, with the labels that each got.

#42 Fix #41, remove dependencies on CCSDS types
  fsw/src/to_lab_app.c
Labels: CCB - Fast Track, IC-20200526, enhancement, ready for CCB

#44 Integration Candidate: 2020-05-27
  README.md
  fsw/src/to_lab_app.c
  fsw/src/to_lab_version.h
Labels: IC-20200527

#45 Fix #32, Make the TO table a proper table
  CMakeLists.txt
  fsw/platform_inc/to_lab_sub_table.h
  fsw/src/to_lab_app.c
  fsw/src/to_lab_app.h
  fsw/src/to_lab_events.h
  fsw/tables/to_lab_sub.c
Labels: CCB-20200610, IC-20200610, code reviewed, enhancement

#46 Integration Candidate: 2020-06-10
  CMakeLists.txt
  README.md
  fsw/platform_inc/to_lab_sub_table.h
  fsw/src/to_lab_app.c
  fsw/src/to_lab_app.h
  fsw/src/to_lab_events.h
  fsw/src/to_lab_version.h
  fsw/tables/to_lab_sub.c
Labels: IC-20200610
