Repository nasa/to_lab, pull requests merged in 2021-02, with the labels that each got.

#76 Fix #68, Remove end of function comments
  fsw/src/to_lab_app.c
Labels: CCB:2021-02-02, CCB:FastTrack, IC:2021-02-02, community

#81 Fix #80, Add static analysis and format check
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  README.md
Labels: CCB:FastTrack, IC:2021-02-02

#83 Fix #82, Add CodeQL analysis to workflow
  .github/workflows/codeql-build.yml
Labels: CCB:FastTrack, continuous-integration

#84 to_lab Integration candidate: 2021-02-02
  .github/workflows/codeql-build.yml
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  README.md
  fsw/src/to_lab_app.c
  fsw/src/to_lab_version.h
Labels: IC:2021-02-02
